version: '3'

services:
  app:
    build: 
      dockerfile: Dockerfile.local
    ports:
      - "5057:5057"
    volumes:
      - .:/App:delegated
    networks:
      - database

networks:
  database: